FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Code/test.Api/test.Api.csproj", "Code/test.Api/"]
COPY ["Code/test.BusinessServices/test.BusinessServices.csproj", "Code/test.BusinessServices/"]
COPY ["Code/test.Data/test.Data.csproj", "Code/test.Data/"]
COPY ["Code/test.BusinessEntities/test.BusinessEntities.csproj", "Code/test.BusinessEntities/"]
COPY ["Code/test.Test.Api/test.Test.Api.csproj", "Code/test.Test.Api/"]
RUN dotnet restore "Code/test.Api/test.Api.csproj"
COPY . .
WORKDIR "/src/Code/test.Api"
RUN dotnet build "test.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "test.Api.csproj" -c Release -o /app/publish

WORKDIR /src

RUN dotnet test --results-directory /app/publish/testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=testresults/ /p:MergeWith=/testresults/coverage/coverage.json  "Code/test.Test.Api/test.Test.Api.csproj"
RUN dotnet test --results-directory /app/publish/testresults --logger "trx;LogFileName=testresults.Api.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=testresults/ /p:MergeWith=/testresults/coverage/coverage.json "Code/test.Test.Business/test.Test.Business.csproj"
